proxies
- name: (ID) Rumahweb 🇮🇩
    server: investor.fb.com
    port: 443
    type: vless
    uuid: 0f1959d2-dc35-41c3-a8ed-522344b7d255
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: investor.fb.com.violetvpn.biz.id
    network: ws
    ws-opts: 
      path: /id-rweb
      headers: 
        Host: investor.fb.com.violetvpn.biz.id
    udp: true
