proxies:
- name: (ID) Akamai Technologies 🇮🇩
  type: vless
  server: investor.fb.com
  port: 443
  uuid: c02173b1-9e72-4abe-8de1-d5948f7ebb08
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /id-akm
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (ID) Amazon.com, Inc 🇮🇩
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 4adf4602-3526-4af9-9f5c-0146332e5ab2
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /id-amz
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (ID) Pt Pusat Media 🇮🇩
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 2e77ab26-b346-4d46-a6f5-4d4169e10b10
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /id-pusat
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (ID) PT. Telekomunikasi 🇮🇩
  type: vless
  server: investor.fb.com
  port: 443
  uuid: ead633ce-3247-4e03-9e81-f47eeba8659c
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /id-tele
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (ID) Rumahweb 🇮🇩
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 1cfb2916-2bc3-4e0a-88d1-65437ac73433
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /id-rweb
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (MY) Gigabit Hosting 🇲🇾
  type: vless
  server: investor.fb.com
  port: 443
  uuid: e9db5ae4-31c2-46ee-8cd9-2e305e23292c
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /my-gb
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (MY) Kaopu Cloud 🇲🇾
  type: vless
  server: investor.fb.com
  port:proxies:
- name: (ID) Akamai Technologies 🇮🇩
  type: vless
  server: investor.fb.com
  port: 443
  uuid: c02173b1-9e72-4abe-8de1-d5948f7ebb08
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /id-akm
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (ID) Amazon.com, Inc 🇮🇩
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 4adf4602-3526-4af9-9f5c-0146332e5ab2
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /id-amz
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (ID) Pt Pusat Media 🇮🇩
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 2e77ab26-b346-4d46-a6f5-4d4169e10b10
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /id-pusat
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (ID) PT. Telekomunikasi 🇮🇩
  type: vless
  server: investor.fb.com
  port: 443
  uuid: ead633ce-3247-4e03-9e81-f47eeba8659c
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /id-tele
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (ID) Rumahweb 🇮🇩
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 1cfb2916-2bc3-4e0a-88d1-65437ac73433
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /id-rweb
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (MY) Gigabit Hosting 🇲🇾
  type: vless
  server: investor.fb.com
  port: 443
  uuid: e9db5ae4-31c2-46ee-8cd9-2e305e23292c
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /my-gb
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (MY) Kaopu Cloud 🇲🇾
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 87d7defb-59df-4c9d-b959-9b464c8935ac
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /my-kao
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) AKILE LTD 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: d004abab-a2c7-4138-a3b8-bcb0d17ae15b
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-akile
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) Contabo Asia 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 22afaa55-3109-406f-a7a5-adef83f15444
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-cntb
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) Digitalocean, LLC 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 021e79e3-8d66-4c6d-963b-a2059ca3b121
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-do
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) Godaddy.com, LLC 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 41812c82-fa1d-4fca-9c0b-b481046105cd
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-gody
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) LEASEWEB SINGAPORE 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 9424a742-55c8-4786-8a23-5d77741367ad
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-lease
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) Melbikomas Uab 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 056bd60d-870b-4e95-9406-45f10ee534bd
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-melbi
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) Oracle Corporation 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 66547260-14da-4719-8f18-6189f2e791bf
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-orcl
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) OVH SAS 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 34985580-3071-472a-a2ae-4c8d85704dab
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-ovh
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) Tcloudnet 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: c46b8874-e192-4f6a-9560-89f385d621df
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-tcloud
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true 443
  uuid: 87d7defb-59df-4c9d-b959-9b464c8935ac
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /my-kao
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) AKILE LTD 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: d004abab-a2c7-4138-a3b8-bcb0d17ae15b
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-akile
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) Contabo Asia 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 22afaa55-3109-406f-a7a5-adef83f15444
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-cntb
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) Digitalocean, LLC 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 021e79e3-8d66-4c6d-963b-a2059ca3b121
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-do
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) Godaddy.com, LLC 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 41812c82-fa1d-4fca-9c0b-b481046105cd
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-gody
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) LEASEWEB SINGAPORE 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 9424a742-55c8-4786-8a23-5d77741367ad
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-lease
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) Melbikomas Uab 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 056bd60d-870b-4e95-9406-45f10ee534bd
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-melbi
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) Oracle Corporation 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 66547260-14da-4719-8f18-6189f2e791bf
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-orcl
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) OVH SAS 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: 34985580-3071-472a-a2ae-4c8d85704dab
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-ovh
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
- name: (SG) Tcloudnet 🇸🇬
  type: vless
  server: investor.fb.com
  port: 443
  uuid: c46b8874-e192-4f6a-9560-89f385d621df
  cipher: none
  skip-cert-verify: true
  servername: investor.fb.com.violetvpn.biz.id
  tls: true
  network: ws
  ws-opts:
    path: /sg-tcloud
    headers:
      Host: investor.fb.com.violetvpn.biz.id
  udp: true
