proxies:
- name: (ID) Pt Pusat Media 🇮🇩
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 42c75c4c-267e-4ed2-a9ea-097a44cb57c9
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts: 
      path: /id-pusat
      headers: 
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true
